copy /Y C:\src\m2\Product\SDK\.net\Microsoft.Azure.Documents.Client\LegacyXPlatform\CustomTypeExtensions.cs .
copy /Y C:\src\m2\Product\SDK\.net\Microsoft.Azure.Documents.Client\LegacyXPlatform\CustomNetCoreTypes.cs .
copy /Y C:\src\m2\Product\SDK\.net\Microsoft.Azure.Documents.Client\LegacyXPlatform\NativeMethods.Darwin.cs .
copy /Y C:\src\m2\Product\SDK\.net\Microsoft.Azure.Documents.Client\LegacyXPlatform\NativeMethods.Unix.cs .
copy /Y C:\src\m2\Product\SDK\.net\Microsoft.Azure.Documents.Client\LegacyXPlatform\NativeMethods.Windows.cs .
copy /Y C:\src\m2\Product\SDK\.net\Microsoft.Azure.Documents.Client\LegacyXPlatform\Platform.cs .
copy /Y C:\src\m2\Product\SDK\.net\Microsoft.Azure.Documents.Client\LegacyXPlatform\PlatformApis.cs .
copy /Y C:\src\m2\Product\Cosmos\Core\Core.Trace\DefaultTrace.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\Common\SharedFiles\DefaultTraceEx.cs .
copy /Y C:\src\m2\Product\Cosmos\Core\Core.Trace\EtwTraceListener.cs .
copy /Y C:\src\m2\Product\Cosmos\Core\Core.Trace\EtwNativeInterop.cs .
copy /Y C:\src\m2\Product\SDK\.net\Microsoft.Azure.Cosmos.Direct\src\BytesSerializer.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\RMResources.* .

copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Schema.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\SchemaBuilderMode.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\SchemaDiscoveryPolicy.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Attachment.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\BoundingBoxSpec.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ClientEncryptionKey.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\KeyWrapMetadata.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Document.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\UserDefinedType.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Offer.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\OfferV2.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\OfferContentV2.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\OfferTypeResolver.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Database.cs     .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\DocumentCollection.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\User.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Permission.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Conflict.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Trigger.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\IndexingPolicy.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\IndexingMode.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\UniqueKeyPolicy.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\GeospatialConfig.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\GeospatialType.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ConflictResolutionPolicy.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ChangeFeedPolicy.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\CollectionBackupPolicy.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\CollectionBackupType.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\OperationKind.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Snapshot.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\SnapshotContent.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\SnapshotKind.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\SnapshotState.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\StoredProcedure.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\UserDefinedFunction.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ConflictResolutionMode.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\IncludedPath.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ExcludedPath.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\CompositePath.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Index.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\IndexJsonConverter.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\IndexKind.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\RangeIndex.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\HashIndex.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\DataType.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\SpatialIndex.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\SpatialType.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\SpatialSpec.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\PermissionMode.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\TriggerType.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\UniqueKey.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\JsonSerializableList.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\RequestOptions.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\AccessCondition.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\AccessConditionType.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\StoreClientFactory.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\LocationNames.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\RegionProximityUtil.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\GeoLinkTypes.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ResourceResponse.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ResourceResponseBase.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\IResourceResponse.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\IResourceResponseBase.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Address.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\DocumentResponse.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\IDocumentResponse.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\PartitionAddressInformation.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\PerProtocolPartitionAddressInformation.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\FeedResource.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\QueryResult.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ApiType.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\AuthorizationTokenType.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\BadRequestException.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\BitUtils.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ClientSideRequestStatistics.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\IClientSideRequestStatistics.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\CloneableStream.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ConcurrentPrng.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\NullSessionContainer.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Collections\DictionaryNameValueCollection.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Collections\DictionaryNameValueCollectionFactory.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Collections\INameValueCollection.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Collections\INameValueCollectionFactory.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Collections\NameValueCollectionWrapper.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Collections\NameValueCollectionWrapperFactory.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ConnectionStateListener.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ConsistencyLevel.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Constants.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\DocumentServiceRequest.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\DocumentServiceRequestContext.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\DocumentServiceRequestExtensions.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\DocumentServiceResponse.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ExceptionExtensions.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\GoneException.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Helpers.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\HttpClientExtension.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\HttpConstants.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\HttpUtility.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\HttpException.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Error.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ICommunicationEventSource.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\InternalSchemaProperties.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\InternalServerErrorException.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\IStoreModel.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ISessionContainer.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ISessionToken.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\IStoreClientFactory.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ITypeResolver.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\JSonSerializable.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Management\ReplicationPolicy.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\MediaIdHelper.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\OperationType.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\NotFoundException.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Paths.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\PathsHelper.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\AddressCacheToken.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\PartitionKey.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\PartitionKeyDefinition.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\PartitionKeyDefinitionVersion.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\PartitionKeyRange.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\PartitionKeyRangeIdentity.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\PartitionKeyRangeStatistics.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\PartitionKeyRangeStatus.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\PartitionKeyStatistics.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\PartitionKind.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Protocol.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ReadPolicy.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\RequestChargeTracker.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\RequestTimeoutException.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ResourceId.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Resource.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ResourceType.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\BoolPartitionKeyComponent.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\InfinityPartitionKeyComponent.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\Int128.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\IPartitionKeyComponent.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\IMasterServiceIdentityProvider.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\MaxNumberPartitionKeyComponent.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\MaxStringPartitionKeyComponent.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\MurmurHash.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\MinNumberPartitionKeyComponent.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\MinStringPartitionKeyComponent.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\NullPartitionKeyComponent.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\NumberPartitionKeyComponent.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\PartitionIsMigratingException.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\PartitionKeyComponentType.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\PartitionKeyInternal.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\PartitionKeyInternalJsonConverter.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\PartitionKeyRangeGoneException.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\Range.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\StringPartitionKeyComponent.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\UndefinedPartitionKeyComponent.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\RuntimeConstants.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\SendingRequestEventArgs.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ReceivedResponseEventArgs.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\SerializationFormattingPolicy.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ServerStoreModel.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ServiceIdentity.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ServiceInteropWrapper.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\StatusCodes.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\StoreResponse.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\StoreResult.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\TimeoutHelper.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\TriggerOperation.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\UInt128.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Undefined.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\UnixDateTimeConverter.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\UriUtility.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\UserAgentContainer.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\WFConstants.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\TaskFactoryExtensions.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\StreamExtension.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\AddressInformation.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\AddressSelector.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\BackoffRetryUtility.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\BarrierRequestHelper.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ConsistencyReader.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ConsistencyWriter.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\GoneAndRetryWithRetryPolicy.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\GoneAndRetryWithRequestRetryPolicy.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\GoneOnlyRequestRetryPolicy.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\IAuthorizationTokenProvider.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\IRetriableResponse.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\IRetryPolicy.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\IRequestRetryPolicy.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\IServiceConfigurationReader.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\IStoreClient.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\QuorumReader.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ReadFeedKeyType.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ReadMode.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\RequestHelper.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\RequestRetryUtility.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ReplicatedResourceClient.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ResourceOperation.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\IAddressResolver.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\IAddressResolverExtension.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Routing\PartitionKeyRangeIsSplittingException.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ServiceUnavailableException.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\SessionTokenHelper.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\SessionTokenMismatchRetryPolicy.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\SimpleSessionToken.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\StoreClient.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\StoreReader.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\TransportClient.cs baseTransportClient.cs
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\TransportPerformanceCounters.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\VectorSessionToken.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\VersionUtility.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ConflictException.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ConnectionEvent.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ContentSerializationFormat.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\EnumerationDirection.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\FanoutOperationState.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\ForbiddenException.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\HttpTransportClient.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\IConnectionStateListener.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\IndexingDirective.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\InvalidPartitionException.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\LockedException.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\MathUtils.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\MethodNotAllowedException.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\MigrateCollectionDirective.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\NetUtil.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\PooledTimer.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\PortReuseMode.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\PreconditionFailedException.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\RemoteStorageType.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\RequestEntityTooLargeException.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\RequestRateTooLargeException.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\RetryWithException.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\Channel.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\ChannelCallArguments.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\ChannelCommonArguments.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\ChannelDictionary.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\ChannelOpenArguments.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\ChannelOpenTimeline.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\ChannelProperties.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\Connection.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\CpuLoad.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\CpuLoadHistory.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\CpuMonitor.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\CpuReaderBase.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\Dispatcher.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\IChannel.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\LbChannelState.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\LinuxCpuReader.cs	 .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\LoadBalancingChannel.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\LoadBalancingPartition.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\ServerKey.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\ServerProperties.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\TransportClient.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\TransportExceptions.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\TransportSerialization.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\UnsupportedCpuReader.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\UserPortPool.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd2\WindowsCpuReader.cs	 .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd\ConnectionPool.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd\ConnectionPoolManager.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd\IConnection.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd\IConnectionDispenser.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd\RntbdConnection.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd\RntbdConnectionDispenser.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd\RntbdConnectionOpenTimers.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd\RntbdConstants.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd\RntbdFuzzConnection.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd\RntbdResponseState.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd\RntbdToken.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\Rntbd\RntbdTokenStream.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\RntbdTransportClient.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\SystemDocumentType.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\TimerPool.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\TransportErrorCode.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\TransportException.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\TransportExceptionCounters.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\UnauthorizedException.cs .
copy /Y C:\src\m2\Product\Microsoft.Azure.Documents\SharedFiles\WebExceptionUtility.cs .
 .